[greeter]
background=/usr/share/backgrounds/minios/login-bg.png
theme-name=Adwaita-dark
icon-theme-name=Adwaita
font-name=Sans 11
xft-antialias=true
indicators=~power
clock-format=%H:%M
position=50%,center 50%,center
default-user-image=/usr/share/backgrounds/minios/user-default.png
show-clock=true

[greeter-hotkeys]
shutdown-shortcut=F11
restart-shortcut=F10
suspend-shortcut=F9
